# ch2 연습장

In [1]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [2]:
import sklearn
print(sklearn.__version__)

0.24.1


## 붓꽃 품종 분류하기 실습(classification)

In [4]:
from sklearn.datasets import load_iris #데이터 세트
from sklearn.tree import DecisionTreeClassifier #의사결정트리
from sklearn.model_selection import train_test_split #데이터 분리

In [6]:
import pandas as pd
iris = load_iris()
iris_data = iris.data
iris_label = iris.target

#데이터 프레임으로 변환(보기쉽게)
df = pd.DataFrame(data=iris_data, columns = iris.feature_names)
df['label']=iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [7]:
#데이터 셋 분리 
train_x, test_x, train_y, test_y = train_test_split(iris_data, iris_label, test_size = 0.2, random_state=11)

In [8]:
#decisiontreeclassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state = 11)

In [9]:
#학습 수행
dt_clf.fit(train_x, train_y)

DecisionTreeClassifier(random_state=11)

In [11]:
#학습이 완료된 객체에서 테스트 데이터로 예측 수행
pred = dt_clf.predict(test_x)

In [14]:
#예측 정확도
from sklearn.metrics import accuracy_score
print(accuracy_score(test_y, pred))

0.9333333333333333


## 내장된 데이터셋 소개

In [17]:
from sklearn.datasets import load_iris
iris_data = load_iris()
print(type(iris_data))

#bunch 클래스는 파이썬 딕셔너리 자료형과 유사

<class 'sklearn.utils.Bunch'>


In [18]:
keys = iris_data.keys()
keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [21]:
#feature name의 타입과 shape
print(type(iris_data.feature_names))
print(len(iris_data.feature_names))
iris_data.feature_names

<class 'list'>
4


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [22]:
#target_names의 타입과 shape
print(type(iris_data.target_names))
print(len(iris_data.target_names))
iris_data.target_names

<class 'numpy.ndarray'>
3


array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [23]:
#data의 타입과 shape
print(type(iris_data.data))
print(len(iris_data.data))
iris_data.data

<class 'numpy.ndarray'>
150


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [24]:
#target의 타입과 shape
print(type(iris_data.target))
print(len(iris_data.target))
iris_data.target

<class 'numpy.ndarray'>
150


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## model selction 모듈 

### train_test_split()

In [29]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier()
iris_data = load_iris()
train_x, test_x, train_y, test_y = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

In [30]:
dt_clf.fit(train_x, train_y)
pred = dt_clf.predict(test_x)
accuracy_score(test_y, pred)

0.9555555555555556

### 교차검증

#### 1) k-fold 교차검증

In [31]:
from sklearn.model_selection import KFold
import numpy as np

In [34]:
iris = load_iris()
features = iris.data
label = iris.target
dt_cfl = DecisionTreeClassifier(random_state = 156)

kfold = KFold(n_splits=5)
cv_accuracy = []

In [35]:
#붓꽃데이터 크기
features.shape[0]

150

In [38]:
n_iter = 0

for train_index, test_index in kfold.split(features):
    train_x, test_x = features[train_index], features[test_index]
    train_y, test_y = label[train_index],label[test_index]
    
    #학습 및 예측
    dt_clf.fit(train_x,train_y)
    pred = dt_clf.predict(test_x)
    n_iter +=1
    
    #반복 시 마다 정확도 측정
    accuracy = np.around(accuracy_score(test_y,pred),4)
    train_size = train_x.shape[0]
    test_size = test_x.shape[0]
    
    print('\n #{0} 교차정확도: {1}, 학습데이터 크기: {2}, 검증데이터 크기: {3}'
         .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증인덱스:{1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    
print("\n 평균 검증 정확도:", np.mean(cv_accuracy))


 #1 교차정확도: 1.0, 학습데이터 크기: 120, 검증데이터 크기: 30
#1 검증인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

 #2 교차정확도: 1.0, 학습데이터 크기: 120, 검증데이터 크기: 30
#2 검증인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

 #3 교차정확도: 0.8333, 학습데이터 크기: 120, 검증데이터 크기: 30
#3 검증인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

 #4 교차정확도: 0.9333, 학습데이터 크기: 120, 검증데이터 크기: 30
#4 검증인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

 #5 교차정확도: 0.7333, 학습데이터 크기: 120, 검증데이터 크기: 30
#5 검증인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

 평균 검증 정확도: 0.89998


#### 2) stratified k-fold

In [40]:
#붓꽃 데이터의 lable 분포 확인
import pandas as pd
iris = load_iris()
iris_df = pd.DataFrame(iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [44]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter +=1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    
    print('교차검증 {}'.format(n_iter))
    print('학습 레이블 분포:\n', label_train.value_counts())
    print('검증 레이블 분포:\n', label_test.value_counts())

교차검증 1
학습 레이블 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
교차검증 2
학습 레이블 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
교차검증 3
학습 레이블 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


In [48]:
dt_clf = DecisionTreeClassifier(random_state=156)
skfold = StratifiedKFold(n_splits=3)

n_iter = 0
cv_accuracy =[]

for train_index, test_index in skfold.split(features, label):
    train_x, test_x = features[train_index], features[test_index]
    train_y, test_y = label[train_index],label[test_index]
    
    #학습 및 예측
    dt_clf.fit(train_x,train_y)
    pred = dt_clf.predict(test_x)
    n_iter +=1
    
    #반복 시 마다 정확도 측정
    accuracy = np.around(accuracy_score(test_y,pred),4)
    train_size = train_x.shape[0]
    test_size = test_x.shape[0]
    
    print('\n #{0} 교차정확도: {1}, 학습데이터 크기: {2}, 검증데이터 크기: {3}'
         .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증인덱스:{1}'.format(n_iter, test_index))
    cv_accuracy.append(accuracy)
    
print("\n 평균 검증 정확도:", np.mean(cv_accuracy))


 #1 교차정확도: 0.98, 학습데이터 크기: 100, 검증데이터 크기: 50
#1 검증인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

 #2 교차정확도: 0.94, 학습데이터 크기: 100, 검증데이터 크기: 50
#2 검증인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

 #3 교차정확도: 0.98, 학습데이터 크기: 100, 검증데이터 크기: 50
#3 검증인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

 평균 검증 정확도: 0.9666666666666667


#### 3) cross_val_score()
교차검증을 한번에 수행

In [54]:
from sklearn.model_selection import cross_val_score

from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state =156)

data = iris_data.data
label = iris_data.target

scores = cross_val_score(dt_clf, data, label, scoring ='accuracy', cv=3)
print('교차검증별 정확도: ', np.round(scores,4))
print('평균정확도: ', np.mean(scores))

교차검증별 정확도:  [0.98 0.94 0.98]
평균정확도:  0.9666666666666667


#### 4) GridSearchCV
교차검증과 하이퍼 파라미터 튜닝을 한번에 수행

In [61]:
from sklearn.model_selection import GridSearchCV

iris_data = load_iris()
train_x, test_x, train_y, test_y = train_test_split(iris_data.data,iris_data.target, test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()

#파라미터를 딕셔너리 형태로 설정
parameters = {'max_depth':[1,2,3], 'min_samples_split': [2,3]}

In [62]:
grid_dtree = GridSearchCV(dtree, param_grid=parameters,cv=3, refit=True)
grid_dtree.fit(train_x, train_y)

scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score','split0_test_score','split1_test_score','split2_test_score']]


params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [63]:
#최적 파라미터
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [64]:
#최고 정확도
grid_dtree.best_score_

0.975

In [66]:
#모델 예측 및 성능 평가
estimator = grid_dtree.best_estimator_

pred= estimator.predict(test_x)
accuracy_score(test_y, pred)

0.9666666666666667

## 데이터 전처리 (preprocessing 모듈)

### 레이블 인코딩
선형회귀와 같은 ml 알고리즘에서는 적용하지 않아야함 \
트리계열 알고리즘은 상관없음

In [1]:
from sklearn.preprocessing import LabelEncoder

items =['이','수','현','선풍기','이','수']

#labelencoder를 객체로 생성한 후, fit 과 transform으로 레이블 인코딩
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

labels

array([2, 1, 3, 0, 2, 1])

In [3]:
#인코딩 클래스
encoder.classes_

array(['선풍기', '수', '이', '현'], dtype='<U3')

In [4]:
#디코딩 원본값
encoder.inverse_transform([2, 1, 3, 0, 2, 1])

array(['이', '수', '현', '선풍기', '이', '수'], dtype='<U3')

## 원핫 인코딩
문자열 -> 숫자형 \
입력값으로 2차원 데이터 필요

In [7]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items =['이','수','현','선풍기','이','수']

#step1: 숫자값 변환
encoder = LabelEncoder()
encoder.fit(items)

#step2: 2차원 데이터로 변환
labels = labels.reshape(-1,1)

#step3: 원핫인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

In [8]:
#원핫 인코딩 데이터
oh_labels.toarray()

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]])

In [9]:
#원핫 인코딩 데이터 차원
oh_labels.shape

(6, 4)

In [12]:
#판다스 api 사용(제일 쉬운 방법)
import pandas as pd
df = pd.DataFrame({'items':['이','수','현','선풍기','이','수']})
pd.get_dummies(df)

items_선풍기  items_수  items_이  items_현
0          0        0        1        0
1          0        1        0        0
2          0        0        0        1
3          1        0        0        0
4          0        0        1        0
5          0        1        0        0

## 피처 스케일링과 정규화

### StandardScaler 

표준화를 지원하기 위한 클래스 \
SVM, 선형회귀, 로지스틱 회귀는 데이터가 가우시안 분포를 가지고 있다고 가정하고 구현되었기 때문에 사전에 표준화를 적용해야함

In [16]:
#iris 데이터로 실습
from sklearn.datasets import load_iris

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns =iris.feature_names)

In [17]:
#데이터 분포 확인
iris_df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [18]:
iris_df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [19]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

#transform 시 데이터 세트가 ndarray로 반환되므로, 데이터 프레임으로 변환
iris_df_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)

In [22]:
#평균, 거의 0에 수렴
iris_df_scaled.mean()

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

In [23]:
#분산, 거의 1에 수렴
iris_df_scaled.var()

sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

### MinMaxScaler 

데이터 값을 0과 1사이의 범위값으로 변환함 \
음수 값이 있으면 -1, 1 값으로 변환함

In [26]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(iris_scaled, columns = iris.feature_names)

In [27]:
iris_df_scaled.min()

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

In [28]:
iris_df_scaled.max()

sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

유의할점: 테스트 데이터의 fit 기준정보는 학습데이터의 fit 기준 정보와 동일하게 설정해야함!\
\
테스트 데이터 셋으로 기준 정보를 설정하게 되면 잘못된 예측결과가 나올 수도

In [32]:
train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled= scaler.transform(train_array)

In [34]:
print('원본  데이터:', np.round(train_array.reshape(-1),2))
print('스케일링 된 데이터', np.round(train_scaled.reshape(-1),2))

원본  데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
스케일링 된 데이터 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [35]:
test_scaled = scaler.transform(test_array)
print('원본  데이터:', np.round(test_array.reshape(-1),2))
print('스케일링 된 데이터', np.round(test_scaled.reshape(-1),2))

원본  데이터: [0 1 2 3 4 5]
스케일링 된 데이터 [0.  0.1 0.2 0.3 0.4 0.5]


가능하다면, 전체 데이터의 스케일링 변환을 적용한 뒤, 학습과 테스트 데이터로 분리